Repository MartinFillon/Corewar, pull requests merged in 2023-05, with the labels that each got.

#57 Write buffer
  .gitignore
  asm/Makefile
  asm/src/create_file.c
  asm/src/main.c
  asm/src/parser/body.c
  asm/src/parser/instruction_parameter.c
  asm/src/parser/parser.c
  champions/abel.s
  champions/pdd.s
  champions/test.s
  champions/tyron.s
  include/asm/asm.h
  include/corewar/op.h
  include/my_str.h
  lib/my_str/modify.c
  lib/my_str/utils.c
Labels: enhancement, assembler

#64 feat: :sparkles: parameters after coding byte, without label address
  asm/Makefile
  asm/src/create_file.c
  asm/src/error_handling/big_endian.c
  asm/src/labels/labels.c
  asm/src/main.c
  asm/src/op.c
  asm/src/parser/body.c
  asm/src/parser/direct.c
  asm/src/parser/header.c
  asm/src/parser/indirect.c
  asm/src/parser/instruction_parameter.c
  asm/src/parser/parser.c
  asm/src/parser/prog_size.c
  asm/src/parser/utils.c
  champions/pdd.s
  champions/too_big.s
  champions/tyron.s
  include/asm/asm.h
  include/asm/body.h
  include/asm/error.h
  include/asm/header.h
  include/asm/utils.h
  include/corewar/op.h
Labels: bug, enhancement, assembler

#74 fix: :bug: crash on empty labels
  asm/src/parser/body.c
  asm/src/parser/header.c
  asm/src/parser/instruction_parameter.c
  asm/src/parser/prog_size.c
Labels: bug, enhancement

#78 feat: :sparkles: implementation of labels
  asm/Makefile
  asm/src/create_file.c
  asm/src/labels/label_address.c
  asm/src/labels/labels.c
  asm/src/main.c
  asm/src/parser/body.c
  asm/src/parser/direct.c
  asm/src/parser/instruction_parameter.c
  asm/src/parser/parser.c
  asm/src/parser/prog_size.c
  include/asm/asm.h
  include/asm/body.h
  include/asm/header.h
  include/asm/labels.h
Labels: enhancement, assembler

#80 fix: :bug: labels are adapted to beg of instructions
  asm/src/labels/label_address.c
  asm/src/labels/labels.c
  asm/src/main.c
  asm/src/parser/instruction_parameter.c
  include/asm/body.h
  include/asm/labels.h
Labels: bug, assembler

#82 fix: :bug: indirect faulty management, false skip
  asm/Makefile
  asm/src/error_handling/arithmetic_bitwise.c
  asm/src/error_handling/cleanup.c
  asm/src/error_handling/fork.c
  asm/src/error_handling/instruction_handling.c
  asm/src/error_handling/load_values_ld.c
  asm/src/error_handling/stores_value_st.c
  asm/src/labels/labels.c
  asm/src/parser/body.c
  asm/src/parser/direct.c
  asm/src/parser/header.c
  asm/src/parser/indirect.c
  asm/src/parser/instruction_parameter.c
  asm/src/parser/parser.c
  asm/src/parser/prog_size.c
  include/asm/asm.h
  include/asm/body.h
  include/asm/error.h
  include/asm/header.h
Labels: bug, assembler

#86 fix: :zap: labels are explicitly compared
  asm/src/labels/labels.c
  asm/src/parser/prog_size.c
  champions/abel.s
Labels: bug, enhancement, assembler

#89 feat: :zap: add error handling for instructions + :bug: missing indirect
  asm/Makefile
  asm/src/error_handling/arithmetic_bitwise.c
  asm/src/error_handling/fork.c
  asm/src/error_handling/instruction_handling.c
  asm/src/error_handling/load_values_ld.c
  asm/src/error_handling/stores_value_st.c
  asm/src/labels/labels.c
  asm/src/parser/indirect.c
  asm/src/parser/instruction_parameter.c
  include/asm/asm.h
  include/asm/error.h
Labels: bug, assembler, instruction

#90 feat: :sparkles: label error handling and coding style
  asm/Makefile
  asm/src/body/direct_params.c
  asm/src/body/indirect_params.c
  asm/src/body/instruction_parameter.c
  asm/src/body/parse_body.c
  asm/src/error_handling/base_actions.c
  asm/src/error_handling/big_endian.c
  asm/src/error_handling/cleanup.c
  asm/src/error_handling/fork_actions.c
  asm/src/error_handling/handle_errors.c
  asm/src/error_handling/impossible_labels.c
  asm/src/header/find_prog_size.c
  asm/src/header/parse_write_header.c
  asm/src/labels/label_address.c
  asm/src/labels/parse_labels.c
  asm/src/op.c
  asm/src/parser.c
  asm/src/utils.c
  include/asm/asm.h
  include/asm/body.h
  include/asm/error.h
  include/asm/labels.h
  include/asm/utils.h
Labels: bug, enhancement, assembler

#94 fix :bug: return 84 on comments after label
  asm/src/body/parse_body.c
  asm/src/error_handling/handle_errors.c
  include/asm/error.h
Labels: bug, enhancement, assembler

#95 85 debug vm - Vm is supposely working
  Makefile
  corewar/Makefile
  corewar/src/executors/add.c
  corewar/src/executors/aff.c
  corewar/src/executors/and.c
  corewar/src/executors/fork.c
  corewar/src/executors/getters/get_arg.c
  corewar/src/executors/getters/get_arg_types.c
  corewar/src/executors/getters/get_direct.c
  corewar/src/executors/getters/get_indirect.c
  corewar/src/executors/ld.c
  corewar/src/executors/ldi.c
  corewar/src/executors/lfork.c
  corewar/src/executors/live.c
  corewar/src/executors/lld.c
  corewar/src/executors/lldi.c
  corewar/src/executors/or.c
  corewar/src/executors/st.c
  corewar/src/executors/sti.c
  corewar/src/executors/sub.c
  corewar/src/executors/utils.c
  corewar/src/executors/writers/read_int.c
  corewar/src/executors/writers/write_int.c
  corewar/src/executors/xor.c
  corewar/src/executors/zjmp.c
  corewar/src/programs/check_program.c
  corewar/src/programs/programs.c
  corewar/src/utils.c
  corewar/src/vm/alive.c
  corewar/src/vm/load_programs.c
  corewar/src/vm/order_programs.c
  corewar/src/vm/run_cycle.c
  corewar/src/vm/run_cycles.c
  corewar/src/vm/vm.c
  include/corewar/arguments.h
  include/corewar/corewar.h
  include/corewar/instructions.h
  tester.py
  tests/Makefile
  tests/instructions_tester.c
  tests/test1.cor
  tests/test10.cor
  tests/test11.cor
  tests/test12.cor
  tests/test13.cor
  tests/test14.cor
  tests/test15.cor
  tests/test16.cor
  tests/test17.cor
  tests/test18.cor
  tests/test19.cor
  tests/test2.cor
  tests/test20.cor
  tests/test3.cor
  tests/test4.cor
  tests/test5.cor
  tests/test6.cor
  tests/test7.cor
  tests/test8.cor
  tests/test9.cor
Labels: bug, virtual machine
